#!/bin/bash
export XDG_CONFIG_HOME="$HOME"/.config
mkdir -p "$XDG_CONFIG_HOME"

ln -sf "$PWD/.config/nvim" "$XDG_CONFIG_HOME"/nvim

ln -sf "$PWD/.zshrc" "$HOME"/.zshrc
ln -sf "$PWD/.tmux.conf" "$HOME"/.tmux.conf


echo "Install brew"
bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
echo "Brew installed"
packages=(
	fd
	ripgrep
	exa
	npm
	starship
	lazygit
	kubectl
	derailed/k9s/k9s
	brew install fluxcd/tap/flux
)

for package in "${packages[@]}"; do
	echo "Installing $package..."
	/home/linuxbrew/.linuxbrew/bin/brew install "$package"
done

echo "All packages from the setup script have been installed."
chsh -s $(which zsh)
