# BEGIN_KITTY_THEME
# Catppuccin-Mocha
# include current-theme.conf
# include ~/.cache/wal/colors-kitty.conf
# include oxocarbon.conf
# END_KITTY_THEME

shell /run/current-system/sw/bin/fish



font_family RobotoMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

hide_window_decorations yes

background_blur 16
background_opacity 0.8

# map ctrl+space>\ launch --location=vsplit
# map ctrl+space>- launch --location=hsplit
#
# map ctrl+space>h resize_window narrower
# map ctrl+space>j resize_window shorter
# map ctrl+space>k resize_window taller
# map ctrl+space>l resize_window wider
#
#
# map ctrl+h neighboring_window left
# map ctrl+l neighboring_window right
# map ctrl+k neighboring_window up
# map ctrl+j neighboring_window down
#
# map ctrl+shift>c new_tab
#
# map ctrl+space>1 goto_tab 1
# map ctrl+space>2 goto_tab 2
# map ctrl+space>3 goto_tab 3
# map ctrl+space>4 goto_tab 4
# map ctrl+space>5 goto_tab 5
# map ctrl+space>6 goto_tab 6
#
tab_bar_style slant
# oxocarbon theme ported to kitty, https://github.com/hbjydev/oxocarbon-kitty
# originally made by nyoom, https://github.com/nyoom-engineering/oxocarbon

foreground #dde1e6
background #161616
selection_foreground #f2f4f8
selection_background #525252

cursor #f2f4f8
cursor_text_color #393939

url_color #ee5396
url_style single

active_border_color #ee5396
inactive_border_color #ff7eb6

bell_border_color #ee5396

wayland_titlebar_color system
macos_titlebar_color system

active_tab_foreground #161616
active_tab_background #ee5396
inactive_tab_foreground #dde1e6
inactive_tab_background #393939
tab_bar_background #161616

color0 #262626
color8 #393939

color1 #ff7eb6
color9 #ff7eb6

color2  #42be65
color10 #42be65

color3  #82cfff
color11 #82cfff

color4  #33b1ff
color12 #33b1ff

color5  #ee5396
color13 #ee5396

color6  #3ddbd9
color14 #3ddbd9

color7  #dde1e6
color15 #ffffff

# vim:ft=conf
