[time]
disabled = true
format = '🕙[\[ $time \]]($style) '
time_format = '%T'
time_range = '10:00:00-14:00:00'


[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = 'bold blue'
symbol = '🅰 '
[aws.region_aliases]
ap-south-1 = 'mumbai'
us-east-1 = 'va'

[nodejs]
disabled = true
symbol = ' '

[bun]
symbol = ' '

[python]
symbol = ' '

[golang]
symbol = '󰟓 '
